version: '3.8'

services:
  app:
    image: php:8.1-fpm-nginx
    container_name: doc-archive-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "25:25"    # Standard SMTP
      - "465:465"  # SMTP over SSL
      - "587:587"  # SMTP with STARTTLS
    environment:
      - APP_NAME=DocArchive
      - APP_ENV=local
      - APP_KEY=base64:Walty6EC2DvM9PnVpSs/OB0ux2BPTqLwIJG0cQUaRgg=
      - APP_DEBUG=true
      - APP_TIMEZONE=Asia/Hong_Kong
      - APP_URL=http://localhost
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=doc_archive
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
      - CACHE_PREFIX=
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=documentarchiveemail@gmail.com
      - MAIL_PASSWORD=ecxnukmtfongsqwv
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=documentarchiveemail@gmail.com
      - MAIL_FROM_NAME=${APP_NAME}
      - POPPLER_PATH=Dependencies/poppler-24.08.0/Library/bin
      - PAYMONGO_PUBLIC_KEY=pk_test_BMFh82W8w2Hi17CPPtxn8Rrx
      - PAYMONGO_SECRET_KEY=sk_test_dHKKkzLNhuKnez4CNvsv98Aw
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: /bin/bash -l -c "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
    networks:
      - app-network
      
  database:
    image: mysql:8.0
    container_name: doc-archive-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=doc_archive
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
